spring:
  main:
      allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/Grupo-07-BDD-OO2-2022
    username: root
    password: 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false      
       